import { MiningVehicle, SafetyAlert, HistoricalReading } from './types';

export const BAILADILA_CENTER = {
  lat: 18.7000,
  lng: 81.2194,
  label: 'Bailadila Iron Ore Mines (Kirandul Complex Pit 14)',
  elevation: 1140,
};

export const MOCK_VEHICLES: MiningVehicle[] = [
  {
    id: 'DMP-104',
    name: 'Komatsu HD785-7',
    number: 'DMP-104',
    type: 'Heavy Dump Truck (100-Ton)',
    driverName: 'Rajeshwar Rao',
    driverId: 'NMDC-BLD-8821',
    zone: 'Kirandul Complex, Pit 14 Bench 6 South',
    status: 'HAULING',
    currentSpeed: 34,
    targetSpeed: 25,
    latitude: 18.7012,
    longitude: 81.2185,
    heading: 145,
    payloadTons: 96.5,
    safetyScore: 87,
    safetyStatus: 'CRITICAL',
  },
  {
    id: 'DMP-108',
    name: 'Caterpillar 777E',
    number: 'DMP-108',
    type: 'Heavy Dump Truck (100-Ton)',
    driverName: 'Amitabh Soren',
    driverId: 'NMDC-BLD-9042',
    zone: 'Kirandul Complex, Incline Haul Road Ramp B',
    status: 'HAULING',
    currentSpeed: 22,
    targetSpeed: 25,
    latitude: 18.6985,
    longitude: 81.2210,
    heading: 320,
    payloadTons: 101.2,
    safetyScore: 52,
    safetyStatus: 'CAUTION',
  },
  {
    id: 'SHV-201',
    name: 'Komatsu PC8000-11',
    number: 'SHV-201',
    type: 'Super Shovel Excavator (800-Ton)',
    driverName: 'Gurmeet Singh',
    driverId: 'NMDC-BLD-4019',
    zone: 'Kirandul Terracotta Pit Bench 6 Loading Face',
    status: 'LOADING',
    currentSpeed: 0,
    targetSpeed: 0,
    latitude: 18.7035,
    longitude: 81.2160,
    heading: 90,
    payloadTons: 0,
    safetyScore: 18,
    safetyStatus: 'SAFE',
  },
  {
    id: 'DMP-112',
    name: 'BEML BH100',
    number: 'DMP-112',
    type: 'Heavy Dump Truck (100-Ton)',
    driverName: 'Sunil Kumar Baghel',
    driverId: 'NMDC-BLD-7650',
    zone: 'Primary Crusher Hopper Approach',
    status: 'UNLOADING',
    currentSpeed: 5,
    targetSpeed: 10,
    latitude: 18.6940,
    longitude: 81.2245,
    heading: 180,
    payloadTons: 98.0,
    safetyScore: 24,
    safetyStatus: 'SAFE',
  },
  {
    id: 'DMP-115',
    name: 'Komatsu HD785-7',
    number: 'DMP-115',
    type: 'Heavy Dump Truck (100-Ton)',
    driverName: 'Dhananjay Mandavi',
    driverId: 'NMDC-BLD-9311',
    zone: 'Kirandul Hairpin Curve 4 (Mist Pocket)',
    status: 'HAULING',
    currentSpeed: 28,
    targetSpeed: 20,
    latitude: 18.6970,
    longitude: 81.2175,
    heading: 210,
    payloadTons: 99.4,
    safetyScore: 74,
    safetyStatus: 'HIGH RISK',
  }
];

export const INITIAL_ALERTS: SafetyAlert[] = [
  {
    id: 'ALT-1092',
    title: 'High Fog Detected',
    description: 'Visibility collapsed to 24m at Hilltop Bench 6. Relative humidity 98% with dense cloud base.',
    severity: 'Critical',
    timestamp: 'Just now',
    vehicleId: 'DMP-104',
    location: 'Kirandul Pit Bench 6',
    acknowledged: false,
  },
  {
    id: 'ALT-1091',
    title: 'Obstacle detected',
    description: '77GHz mmWave radar detected stationary service vehicle in haul lane 16m ahead.',
    severity: 'Critical',
    timestamp: '2 mins ago',
    vehicleId: 'DMP-104',
    location: 'Ramp B Switchback',
    acknowledged: false,
  },
  {
    id: 'ALT-1090',
    title: 'Low Visibility',
    description: 'Optical transmissometer reports fog index > 85%. Speed governor threshold enforced to 20 km/h.',
    severity: 'Warning',
    timestamp: '6 mins ago',
    vehicleId: 'DMP-115',
    location: 'Hairpin Curve 4',
    acknowledged: false,
  },
  {
    id: 'ALT-1089',
    title: 'Unsafe Vehicle Speed',
    description: 'Vehicle traveling at 43 km/h on wet 8% downhill monsoon gradient. Governed limit is 25 km/h.',
    severity: 'Critical',
    timestamp: '11 mins ago',
    vehicleId: 'DMP-104',
    location: 'Kirandul Bench 6 Ramp',
    acknowledged: true,
  },
  {
    id: 'ALT-1088',
    title: 'Sudden obstacle detected',
    description: 'LiDAR point cloud detected falling rock boulder on outer berm track edge.',
    severity: 'Warning',
    timestamp: '18 mins ago',
    vehicleId: 'DMP-108',
    location: 'Incline Ramp B',
    acknowledged: true,
  },
  {
    id: 'ALT-1087',
    title: 'Rain detected',
    description: 'Weather telemetry measured 6.2 mm/hr monsoon precipitation. Ground friction index reduced by 40%.',
    severity: 'Information',
    timestamp: '25 mins ago',
    vehicleId: 'ALL-FLEET',
    location: 'Deposit 14 Weather Station',
    acknowledged: true,
  },
  {
    id: 'ALT-1086',
    title: 'Haul dangerous path detected',
    description: 'Runoff trench washed mud over bench edge line. Lane guidance system recalibrated.',
    severity: 'Warning',
    timestamp: '34 mins ago',
    vehicleId: 'DMP-112',
    location: 'Crusher Approach',
    acknowledged: true,
  }
];

export const INITIAL_HISTORICAL_LOGS: HistoricalReading[] = [
  { id: 'LOG-501', time: '10:45:00', visibility: 25, fog: 92, speed: 43, radar: 16, temperature: 22.4, status: 'CRITICAL', vehicleId: 'DMP-104' },
  { id: 'LOG-502', time: '10:44:30', visibility: 28, fog: 89, speed: 38, radar: 19, temperature: 22.4, status: 'CRITICAL', vehicleId: 'DMP-104' },
  { id: 'LOG-503', time: '10:44:00', visibility: 32, fog: 84, speed: 32, radar: 24, temperature: 22.5, status: 'WARNING', vehicleId: 'DMP-104' },
  { id: 'LOG-504', time: '10:43:30', visibility: 45, fog: 71, speed: 28, radar: 31, temperature: 22.6, status: 'WARNING', vehicleId: 'DMP-108' },
  { id: 'LOG-505', time: '10:43:00', visibility: 52, fog: 65, speed: 25, radar: 38, temperature: 22.7, status: 'WARNING', vehicleId: 'DMP-108' },
  { id: 'LOG-506', time: '10:42:30', visibility: 85, fog: 38, speed: 24, radar: 48, temperature: 23.0, status: 'NORMAL', vehicleId: 'DMP-112' },
  { id: 'LOG-507', time: '10:42:00', visibility: 92, fog: 32, speed: 22, radar: 52, temperature: 23.1, status: 'NORMAL', vehicleId: 'DMP-112' },
  { id: 'LOG-508', time: '10:41:30', visibility: 110, fog: 22, speed: 20, radar: 55, temperature: 23.2, status: 'NORMAL', vehicleId: 'DMP-115' },
  { id: 'LOG-509', time: '10:41:00', visibility: 29, fog: 88, speed: 29, radar: 18, temperature: 22.3, status: 'CRITICAL', vehicleId: 'DMP-115' },
  { id: 'LOG-510', time: '10:40:30', visibility: 34, fog: 81, speed: 27, radar: 22, temperature: 22.4, status: 'WARNING', vehicleId: 'DMP-115' },
];
